package Gestion_BDD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Gestion_BDD extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_BDD
     */
    public Gestion_BDD() {
        setTitle("Gestion de la base de données");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Txt_Id = new javax.swing.JTextField();
        Txt_Nom_produit = new javax.swing.JTextField();
        Txt_Quantite = new javax.swing.JTextField();
        Txt_prix_min = new javax.swing.JTextField();
        Txt_prix_max = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btn_Modifier = new javax.swing.JButton();
        Btn_Supprimer = new javax.swing.JButton();
        Btn_Premier = new javax.swing.JButton();
        Btn_Precedent = new javax.swing.JButton();
        Btn_Suivant = new javax.swing.JButton();
        Btn_Dernier = new javax.swing.JButton();
        btn_Ajouter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Produits = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Txt_Rechercher = new javax.swing.JTextField();
        Btn_Rechercher = new javax.swing.JButton();
        Btn_Afficher = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_IdActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Nom produit");

        jLabel3.setText("Quantité");

        jLabel4.setText("Prix min");

        jLabel5.setText("Prix max");

        Btn_Modifier.setText("Modifier");
        Btn_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModifierActionPerformed(evt);
            }
        });

        Btn_Supprimer.setText("Supprimer");
        Btn_Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SupprimerActionPerformed(evt);
            }
        });

        Btn_Premier.setText("<<");
        Btn_Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PremierActionPerformed(evt);
            }
        });

        Btn_Precedent.setText("<");
        Btn_Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_PrecedentActionPerformed(evt);
            }
        });

        Btn_Suivant.setText(">");
        Btn_Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SuivantActionPerformed(evt);
            }
        });

        Btn_Dernier.setText(">>");
        Btn_Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DernierActionPerformed(evt);
            }
        });

        btn_Ajouter.setText("Ajouter");
        btn_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Btn_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Supprimer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Txt_Nom_produit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_Quantite, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_prix_min, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt_prix_max, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_Premier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Precedent)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Suivant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Dernier)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_prix_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_prix_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Premier)
                    .addComponent(Btn_Precedent)
                    .addComponent(Btn_Suivant)
                    .addComponent(Btn_Dernier))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        Table_Produits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom produit", "Quantité", "Prix min", "Prix max"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Produits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Produits);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Id");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Nom");

        Btn_Rechercher.setText("Rechercher");
        Btn_Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RechercherActionPerformed(evt);
            }
        });

        Btn_Afficher.setText("Afficher");
        Btn_Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AfficherActionPerformed(evt);
            }
        });

        jLabel6.setText("Recherche par:");

        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(6, 6, 6)
                        .addComponent(Txt_Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Afficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Rechercher)
                                    .addComponent(jRadioButton1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn_Afficher))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jRadioButton2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Txt_Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Modification d'un produit
    private void Btn_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModifierActionPerformed
try {
    
if (JOptionPane.showConfirmDialog(null, "Confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
    St.executeUpdate("UPDATE Liste_produits SET Nom_produit='"+Txt_Nom_produit.getText()+"',Quantite='"+Txt_Quantite.getText()+"',Prix_min='"+Txt_prix_min.getText()+"',prix_max='"+Txt_prix_max.getText()+"' WHERE Id="+Txt_Id.getText()+"");
    Afficher_Produits();
}
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Veuillez remplir le champ Id !");
}
    }//GEN-LAST:event_Btn_ModifierActionPerformed
// Supprimer Produit
    private void Btn_SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SupprimerActionPerformed
try {
    if (JOptionPane.showConfirmDialog(null, "Confirmer la suppression","Suppression d'un produit",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
    if (Txt_Id.getText().length() !=0){
    St.executeUpdate("DELETE from Liste_produits WHERE ID="+Txt_Id.getText()+"");
    Afficher_Produits();
    }else {
        JOptionPane.showMessageDialog(null, "");
    }
}
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Erreur de supression\n"+e.getMessage());
}
    }//GEN-LAST:event_Btn_SupprimerActionPerformed

    private void Btn_RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RechercherActionPerformed
try {
    dt.setRowCount(0);
    if (jRadioButton1.isSelected()){
        Rs = St.executeQuery("Select * from Liste_produits WHERE Id = "+Txt_Rechercher.getText());
    }else {
        Rs = St.executeQuery("Select * from Liste_produits WHERE Nom_produit = '"+Txt_Rechercher.getText()+"'");
    }
    
    while (Rs.next()){
        Id = Rs.getInt(1);
        Nom_produit = Rs.getString(2);
        Quantite = Rs.getInt(3);
        Prix_min = Rs.getDouble(4);
        Prix_max = Rs.getDouble(5);
            Object[] pdt={Id,Nom_produit,Quantite,Prix_min,Prix_max};
            dt.addRow(pdt);
    }
        if (dt.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Aucun produit");
            Afficher_Produits();
        }else {
            i = 0;
            Deplacer_Produits(i);
        }
    
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Erreur Boutton Recherche\n"+e.getMessage());
}
    }//GEN-LAST:event_Btn_RechercherActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    cnx = DriverManager.getConnection("jdbc:odbc:Produits_link");
    St = cnx.createStatement();
    buttonGroup1.add(jRadioButton1);
    buttonGroup1.add(jRadioButton2);
    jRadioButton1.setSelected(true);
    
    
     dt = new DefaultTableModel();
       dt.addColumn("Id");
       dt.addColumn("Nom_produit");
       dt.addColumn("Quantite");
       dt.addColumn("Prix_min");
       dt.addColumn("Prix_max");
       Table_Produits.setModel(dt);
       Afficher_Produits();
       i = 0;
       Deplacer_Produits(i);
}catch (Exception e){
JOptionPane.showMessageDialog(null, "Erreur de connection\n"+e.getMessage());
}
    }//GEN-LAST:event_formWindowOpened

    private void Deplacer_Produits(int i){
        try{
            if (i == 0) {
                Btn_Precedent.setEnabled(false);
                Btn_Suivant.setEnabled(true);
            } else if (i == dt.getRowCount()-1) {
                Btn_Precedent.setEnabled(true);
                Btn_Suivant.setEnabled(false);
            }else {
                Btn_Precedent.setEnabled(true);
                Btn_Suivant.setEnabled(true);
            }if (dt.getRowCount()==1 ){
                Btn_Precedent.setEnabled(false);
                Btn_Suivant.setEnabled(false);
            }else if (dt.getRowCount()==0){
                Btn_Precedent.setEnabled(false);
                Btn_Suivant.setEnabled(false);
                Txt_Id.setText("null");
                Txt_Nom_produit.setText("null");
                Txt_Quantite.setText("null");
                Txt_prix_min.setText("null");
                Txt_prix_max.setText("null");
            }
            
            Txt_Id.setText(dt.getValueAt(i, 0).toString());
            Txt_Nom_produit.setText(dt.getValueAt(i, 1).toString());
            Txt_Quantite.setText(dt.getValueAt(i, 2).toString());
            Txt_prix_min.setText(dt.getValueAt(i, 3).toString());
            Txt_prix_max.setText(dt.getValueAt(i, 4).toString());
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Erreur déplacement produits\n"+e.getMessage());
    }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PremierActionPerformed
try {
    i =0;
    Deplacer_Produits(i);
}catch (Exception e){
        JOptionPane.showMessageDialog(null,"Erreur premier !\n"+e.getMessage());
    
    }//GEN-LAST:event_Btn_PremierActionPerformed
    }
    private void Btn_PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_PrecedentActionPerformed
try {
    i--;
    Deplacer_Produits(i);
}catch (Exception e){
        JOptionPane.showMessageDialog(null,"Erreur premier !\n"+e.getMessage());
    
    }
    }//GEN-LAST:event_Btn_PrecedentActionPerformed

    private void Btn_SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SuivantActionPerformed
try {
    i++;
    Deplacer_Produits(i);
}catch (Exception e){
        JOptionPane.showMessageDialog(null,"Erreur premier !\n"+e.getMessage());
    
    }
    }//GEN-LAST:event_Btn_SuivantActionPerformed

    private void Btn_DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DernierActionPerformed
try {
    i = dt.getRowCount()-1;
    Deplacer_Produits(i);
}catch (Exception e){
        JOptionPane.showMessageDialog(null,"Erreur premier !\n"+e.getMessage());
    
    }
    }//GEN-LAST:event_Btn_DernierActionPerformed

    private void Table_ProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ProduitsMouseClicked
try {
    i = Table_Produits.getSelectedRow();
    Deplacer_Produits(i);
}catch (Exception e){
    JOptionPane.showMessageDialog(null,"Erreur selection produit\n"+e.getMessage());
}
    }//GEN-LAST:event_Table_ProduitsMouseClicked

// Ajout d'un produit
    private void btn_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AjouterActionPerformed
try {
    // Vérification si le produit déja existe dans la bdd
    boolean b=false;
    for (int j=0;j<dt.getRowCount();j++){
        if(Integer.parseInt(Txt_Id.getText()) == dt.getValueAt(j, 0)){
            b = true;
            break;
        }
    }
    
    if (b == false){
        St.executeUpdate("Insert into Liste_produits Values('"+Txt_Id.getText()+"','"+Txt_Nom_produit.getText()+"','"+Txt_Quantite.getText()+"','"+Txt_prix_min.getText()+"','"+Txt_prix_max.getText()+"')");
        Afficher_Produits();
        JOptionPane.showMessageDialog(null, "Le produit est ajouté");
    }else {
        JOptionPane.showMessageDialog(null, "L'identifiant existe déja  dans la Bdd");
        Txt_Id.setText("");
    }
    
}catch (Exception e){
    JOptionPane.showMessageDialog(null,"Erreur Ajout d'un produit\n"+e.getMessage());
}
    }//GEN-LAST:event_btn_AjouterActionPerformed

    private void Btn_AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AfficherActionPerformed
try {
    
}catch (Exception e){
    JOptionPane.showMessageDialog(null,"Erreur Boutton Afficher produit\n"+e.getMessage());
}
    }//GEN-LAST:event_Btn_AfficherActionPerformed

    private void Txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_IdActionPerformed

private void Afficher_Produits(){
try{
    dt.setRowCount(0);
    Rs = St.executeQuery("Select * From Liste_produits ") ;
    while (Rs.next()){
        Id = Rs.getInt("Id");
        Nom_produit = Rs.getString("Nom_produit");
        Quantite = Rs.getInt("Quantite");
        Prix_min = Rs.getDouble("Prix_min");
        Prix_max = Rs.getDouble("Prix_max");
        Object[] prd = {Id,Nom_produit,Quantite,Prix_min,Prix_max};
        dt.addRow(prd);
    }

    
}catch (Exception e){
    JOptionPane.showMessageDialog(null,"Erreur affichage de la liste des produit\n"+e.getMessage());
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Gestion_BDD().setVisible(true);
            }
        });
    }
    // Déclaration des variables
    private Connection cnx;
    private Statement St;
    private ResultSet Rs;
    private DefaultTableModel dt;
    private int i,Id,Quantite;
    private String Nom_produit;
    private double Prix_min,Prix_max;
    // Variables declaration - do not modify    private String Nom_produit;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Afficher;
    private javax.swing.JButton Btn_Dernier;
    private javax.swing.JButton Btn_Modifier;
    private javax.swing.JButton Btn_Precedent;
    private javax.swing.JButton Btn_Premier;
    private javax.swing.JButton Btn_Rechercher;
    private javax.swing.JButton Btn_Suivant;
    private javax.swing.JButton Btn_Supprimer;
    private javax.swing.JTable Table_Produits;
    private javax.swing.JTextField Txt_Id;
    private javax.swing.JTextField Txt_Nom_produit;
    private javax.swing.JTextField Txt_Quantite;
    private javax.swing.JTextField Txt_Rechercher;
    private javax.swing.JTextField Txt_prix_max;
    private javax.swing.JTextField Txt_prix_min;
    private javax.swing.JButton btn_Ajouter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
